import 'regenerator-runtime/runtime';
import { sortDocsWithLocation } from '../src/iframe/prediction';

describe('sortDocsWithLocation', () => {
  test('should show the correct main document', () => {
    const location = {
      href: 'http://localhost:3000/blog',
      ancestorOrigins: {},
      origin: 'http://localhost:3000',
      protocol: 'http:',
      host: 'localhost:3000',
      hostname: 'localhost',
      port: '3000',
      pathname: '/blog',
      search: '',
      hash: ''
    };
    const wrongOrder = [
      {
        editorUrl: 'https://fsake.prismic.io/documents~c=published&l=en-us/shouldbesecond/',
        id: 'shouldbesecond',
        isDocumentLink: false,
        queryTotal: 1,
        singleton: true,
        status: 'live',
        summary: 'Categories',
        title: 'Navbar',
        updated: 1625563799012,
        urls: ['/blog'],
        weight: 3,
      },
      {
        editorUrl: 'https://fake.prismic.io/documents~c=published&l=en-us/shouldbefirst/',
        id: 'shouldbefirst',
        isDocumentLink: false,
        queryTotal: 1,
        singleton: true,
        status: 'live',
        summary: 'Featured',
        title: 'Blog Home',
        updated: 1625563799291,
        urls: ['/blog'],
        weight: 3,
      }
    ];

    const result = sortDocsWithLocation(wrongOrder, location);

    expect(result[0].title).toBe('Blog Home');
  });

  test('when records are similar it will try try and match the pathname', () => {
    const location = {
      href: 'http://localhost:3000/blog',
      ancestorOrigins: {},
      origin: 'http://localhost:3000',
      protocol: 'http:',
      host: 'localhost:3000',
      hostname: 'localhost',
      port: '3000',
      pathname: '/blog',
      search: '',
      hash: ''
    };

    const wrongOrder = [
      {
        editorUrl: 'https://fsake.prismic.io/documents~c=published&l=en-us/shouldbesecond/',
        id: 'shouldbesecond',
        isDocumentLink: false,
        queryTotal: 1,
        singleton: true,
        status: 'live',
        summary: 'Categories',
        title: 'Navbar',
        updated: 0,
        urls: ['/blog'],
        weight: 3,
      },
      {
        editorUrl: 'https://fake.prismic.io/documents~c=published&l=en-us/shouldbefirst/',
        id: 'shouldbefirst',
        isDocumentLink: false,
        queryTotal: 1,
        singleton: true,
        status: 'live',
        summary: 'Featured',
        title: 'Blog Home',
        updated: 0,
        urls: ['/blog'],
        weight: 3,
      }
    ];

    const result = sortDocsWithLocation(wrongOrder, location);

    expect(result[0].title).toBe('Blog Home');
  });

  test('title matching with the location pathname should supersede date', () => {
    const location = {
      href: 'http://localhost:3000/blog',
      ancestorOrigins: {},
      origin: 'http://localhost:3000',
      protocol: 'http:',
      host: 'localhost:3000',
      hostname: 'localhost',
      port: '3000',
      pathname: '/blog',
      search: '',
      hash: ''
    };
    const docs = [
      {
        editorUrl: 'https://fsake.prismic.io/documents~c=published&l=en-us/shouldbesecond/',
        id: 'shouldbesecond',
        isDocumentLink: false,
        queryTotal: 1,
        singleton: true,
        status: 'live',
        summary: 'Categories',
        title: 'Navbar',
        updated: 1,
        urls: ['/blog'],
        weight: 3,
      },
      {
        editorUrl: 'https://fake.prismic.io/documents~c=published&l=en-us/shouldbefirst/',
        id: 'shouldbefirst',
        isDocumentLink: false,
        queryTotal: 1,
        singleton: true,
        status: 'live',
        summary: 'Featured',
        title: 'Blog Home',
        updated: 0,
        urls: ['/blog'],
        weight: 3,
      }
    ];

    const result = sortDocsWithLocation(docs, location);

    expect(result[0].title).toBe('Blog Home');
  });

  test('Documents with out uids', () => {
    const location = {
      href: 'http://localhost:3000/docs/technologies/home-prismic-and-nextjs',
      ancestorOrigins: {},
      origin: 'http://localhost:3000',
      protocol: 'http:',
      host: 'localhost:3000',
      hostname: 'localhost',
      port: '3000',
      pathname: '/docs/technologies/home-prismic-and-nextjs',
      search: '',
      hash: ''
    };
    const docs = [
      {
        id: 'Xej8gREAACQApSU3',
        urls: [
          '/docs/technologies/publish-your-library-nuxtjs',
          '/docs/technologies/deployment-node.js',
          '/docs/technologies/query-by-tags-rest-api',
          '/docs/technologies/vue-preview',
          '/docs/templating-boolean-field-ruby',
          '/docs/technologies/query-by-id-or-uid-graphql',
          '/docs/technologies/rendering-the-date-field-gatsby',
          '/docs/core-concepts/boolean',
          '/docs/technologies/query-a-single-document-gatsby-birkir',
          '/docs/integrating-with-an-existing-project-javascript',
          '/docs/technologies/vue-advanced-queries',
          '/docs/technologies/lifecycle-hooks-nextjs',
          '/docs/technologies/tutorial-1-launch-the-project-gatsby',
          '/docs/query-predicate-reference-javascript',
          '/docs/prismic-core-concepts-introduction',
          '/docs/technologies/templating-date-field-java',
          '/docs/core-concepts/migrate-html-or-markdown-to-prismic',
          '/docs/prismic-core-concepts-content-querying',
          '/docs/nextjs',
          '/docs/technologies/tutorial-1-launch-project-gatsby',
          '/docs/technologies/paginate-your-results-gatsby-birkir',
          '/docs/technologies/gatsby-tutorial-3-convert-the-homepage-main-content',
          '/docs/technologies/seo-with-vuejs-and-prismic',
          '/docs/technologies/templating-date-field-javascript',
          '/docs/technologies/gatsby-tutorial-1-launching-the-project',
          '/docs/technologies/gatsby-birkir-tutorial-3-convert-the-homepage-main-content',
          '/docs/technologies/gatsby-birkir-home',
          '/docs/technologies/fulltext-search-javascript',
          '/docs/technologies/build-a-page-with-slices-nuxtjs',
          '/docs/technologies/issues-with-gatsby-queries',
          '/docs/technologies/templating-uid-field-nodejs',
          '/docs/technologies/gatsby-anatomy-of-a-query',
          '/docs/technologies/rendering-the-date-field-reactjs',
          '/docs/technologies/rendering-the-timestamp-field-reactjs',
          '/docs/technologies/fragments-in-gatsby',
          '/docs/technologies/tutorial-3-create-homepage-slices-gatsby',
          '/docs/technologies/the-response-object-nodejs',
          '/docs/technologies/query-by-tag-nodejs',
          '/docs/technologies/html-serializer-nodejs',
          '/docs/technologies/template-fields-gatsby',
          '/docs/getting-started-vuejs',
          '/docs/technologies/add-a-community-default-library-to-your-project-nuxtjs',
          '/docs/technologies/create-a-page-add-content--publish-nextjs',
          '/',
          '/docs/technologies/add-the-slice-zone-to-your-page-nuxtjs',
          '/docs/technologies/fetch-linked-document-fields-nodejs',
          '/docs/prismic-and-nextjs',
          '/docs/technologies/the-future-of-prismic-and-gatsby',
          '/docs/technologies/templating-number-field-vuejs',
          '/docs/technologies/navbars-footers-and-menus-nextjs',
          '/docs/technologies/query-by-a-field-javascript',
          '/docs/technologies/getting-started-with-slice-machine-nextjs',
          '/docs/technologies/previews-and-the-prismic-toolbar-reactjs',
          '/docs/technologies/rendering-a-link-or-content-relationship-field-reactjs',
          '/docs/docs',
          '/docs/the-document-object-nodejs',
          '/docs/prismic-core-concepts-content-templating',
          '/docs/technologies/customization-nextjs',
          '/docs/technologies/retrieve-prismic-content-fields-gatsby',
          '/docs/query-by-tag-java',
          '/docs/technologies/templating-link-and-content-relationship-fields-javascript',
          '/docs/technologies/the-response-object-javascript',
          '/docs/technologies/run-your-project-nuxtjs',
          '/docs/technologies/query-by-language-gatsby',
          '/docs/technologies/date-and-time-based-predicate-reference-rest-api',
          '/docs/the-rest-api-browser',
          '/docs/technologies/getting-started-nextjs',
          '/docs/technologies/query-by-language-rest-api',
          '/docs/technologies/rendering-the-color-field-reactjs',
          '/docs/technologies/add-content-and-query-the-cms-nuxtjs',
          '/docs/technologies/html-serializer-javascript',
          '/docs/technologies/use-multiple-predicates-nodejs',
          '/docs/technologies/retrieve-the-metadata-gatsby-birkir',
          '/docs/gatsby-tutorial-6-setting-up-previews',
          '/docs/asdf',
          '/docs/technologies/query-predicate-reference-javascript',
          '/docs/technologies/previews-nextjs',
          '/docs/technologies/previews-and-the-prismic-toolbar-nodejs',
          '/docs/technologies/templating-the-rich-text-title-fields-ruby',
          '/docs/technologies/build-a-page-with-slices-nextjs',
          '/docs/technologies/adding-a-storybook-nuxtjs',
          '/docs/technologies/rendering-the-slice-zone-gatsby',
          '/docs/technologies/rendering-the-geopoint-field-gatsby-birkir',
          '/docs/migrating-to-the-nuxtjs-prismic-module-vuejs',
          '/docs/technologies/recreate-banner-as-component-nuxtjs',
          '/docs/technologies/quick-start-nextjs',
          '/docs/technologies/recreate-the-banner-as-a-component-nuxtjs',
          '/docs/technologies/add-content-models-cms-nuxtjs',
          '/docs/technologies/gatsby-getting-started-tutorials',
          '/docs/technologies/paginate-the-results-gatsby',
          '/docs/date-time-based-predicate-reference-javascript',
          '/docs/technologies/gatsby-tutorial-2-convert-the-static-homepage-banner',
          '/docs/technologies/query-all-your-documents-gatsby',
          '/docs/technologies/prismic-gatsby-source-plugin',
          '/docs/technologies/run-a-pre-configured-project-nuxtjs',
          '/docs/technologies/the-document-object-reactjs',
          '/docs/technologies/query-a-singleton-type-nextjs',
          '/docs/technologies/fulltext-search-nodejs',
          '/docs/query-by-id-or-uid-java',
          '/docs/technologies/query-by-language-javascript',
          '/docs/technologies/query-by-content-relationship-nodejs',
          '/docs/technologies/query-by-date-rest-api',
          '/docs/technologies/deploying-your-gatsby-website-birkir',
          '/docs/technologies/query-by-id-or-uid-nodejs',
          '/docs/technologies/templating-number-field-javascript',
          '/docs/technologies/query-all-your-documents-reactjs',
          '/docs/technologies/storybook-nuxtjs',
          '/docs/query-all-documents-java',
          '/docs/technologies/sample-blog-gatsby',
          '/docs/technologies/install-the-cli',
          '/docs/technologies/previews-and-the-prismic-toolbar-php',
          '/docs/getting-started-with-nextjs',
          '/docs/technologies/how-to-query-the-api-php',
          '/docs/technologies/create-your-own-slices-components-nextjs',
          '/docs/integrate-prismic-with-an-existing-project-ruby',
          '/docs/technologies/templating-date-field-vuejs',
          '/docs/templating-group-field-ruby',
          '/docs/technologies/sample-multi-lang-site-gatsby',
          '/docs/core-concepts/test-page',
          '/docs/technologies/getting-started-laravel',
          '/docs/technologies/gatsby-birkir-tutorial-6-setting-up-previews',
          '/docs/technologies/templating-embed-field-javascript',
          '/docs/technologies/templating-boolean-field-vuejs',
          '/docs/technologies/query-by-language-vuejs',
          '/docs/technologies/rendering-the-number-field-gatsby-birkir',
          '/docs/technologies/use-multiple-predicates-vuejs',
          '/docs/technologies/templating-boolean-field-javascript',
          '/docs/technologies/rendering-links-or-link-to-media-fields-gatsby',
          '/docs/technologies/create-a-new-nuxt-app',
          '/docs/technologies/getting-started-examples-simple-nuxtjs',
          '/docs/technologies/rendering-the-select-field-gatsby-birkir',
          '/docs/technologies/template-slices-gatsby',
          '/docs/start-a-prismic-project-from-scratch-with-reactjs',
          '/docs/technologies/languages-localization-gatsby',
          '/docs/technologies/how-to-query-the-api-vuejs',
          '/docs/core-concepts/how-to-export-content',
          '/docs/technologies/query-by-content-relationship-vuejs',
          '/docs/technologies/getting-started-with-slice-machine-nuxtjs',
          '/docs/core-concepts/collections',
          '/docs/core-concepts/import-bulk-update',
          '/docs/technologies/templating-links-gatsby',
          '/docs/fulltext-search-java',
          '/docs/technologies/adding-the-slicezone-component-nextjs',
          '/docs',
          '/docs/technologies/pagination-for-results-nodejs',
          '/docs/technologies/templating-embed-field-nodejs',
          '/docs/technologies/deployement-reactjs',
          '/docs/technologies/query-options-reference-nodejs',
          '/docs/technologies/pagination-for-results-javascript',
          '/docs/technologies/templating-geopoint-field-javascript',
          '/docs/technologies/link-resolver-vuejs',
          '/docs/technologies/templating-select-field-vuejs',
          '/docs/technologies/query-by-id-or-uid-reactjs',
          '/docs/technologies/query-by-content-relationship-javascript',
          '/docs/technologies/templating-group-field-nodejs',
          '/docs/core-concepts/slices',
          '/docs/technologies/templating-color-field-javascript',
          '/docs/technologies/query-by-a-content-relationship-or-link-field-graphql',
          '/docs/retrieve-slice-content-graphql',
          '/docs/technologies/tutorial-5-add-the-navigation-gatsby',
          '/docs/core-concepts/publish-a-new-document',
          '/docs/technologies/gatsby-tutorial-4-adding-repeatable-pages',
          '/docs/gatsby-tutorial-3-convert-the-homepage-main-content',
          '/docs/technologies/add-navigation-nextjs',
          '/docs/technologies/query-options-reference-ruby',
          '/docs/technologies/query-by-a-content-relationship-field-reactjs',
          '/docs/concepts',
          '/docs/technologies/rendering-the-boolean-field-reactjs',
          '/docs/query-by-a-field-javascript',
          '/docs/technologies/use-multiple-predicates-javascript',
          '/docs/technologies/query-by-tag-javascript',
          '/docs/technologies/rendering-the-boolean-field-gatsby',
          '/docs/the-future-of-prismic-and-gatsby',
          '/docs/technologies/home-prismic-and-nextjs',
          '/docs/technologies/retrieve-slice-content-graphql',
          '/docs/technologies/rendering-the-group-field-gatsby-birkir',
          '/docs/technologies/explore-more-vuejs',
          '/docs/technologies/nodejs',
          '/docs/technologies/query-by-a-field-reactjs',
          '/docs/technologies/integrating-with-an-existing-project-vuejs',
          '/docs/technologies/templating-timestamp-field-laravel',
          '/docs/technologies/html-serializer-gatsby-birkir',
          '/docs/technologies/query-by-date-vuejs',
          '/docs/technologies/rendering-slices-reactjs',
          '/docs/technologies/introduction-to-the-content-query-api',
          '/docs/technologies/prismic-dom-technical-reference',
          '/docs/technologies/query-options-reference-php',
          '/docs/technologies/the-route-resolver-nextjs',
          '/docs/technologies/templating-images-gatsby',
          '/docs/technologies/query-predicate-reference-vuejs',
          '/docs/core-concepts/rich-text-title',
          '/docs/technologies/install-the-prismic-cli-nextjs',
          '/docs/technologies/publish-a-slice-library-nuxtjs',
          '/docs/technologies/the-slice-builder-nuxtjs',
          '/docs/technologies/templating-embed-field-vuejs',
          '/docs/technologies/templating-timestamp-field-vuejs',
          '/docs/technologies/multilingual-templating-nuxt',
          '/docs/technologies/convert-everything-to-components-nuxtjs',
          '/docs/technologies/query-a-single-type-document-nodejs',
          '/docs/fetch-linked-document-fields-vuejs',
          '/docs/technologies/the-response-object-vuejs',
          '/docs/technologies/migrating-to-the-nuxtjs-prismic-module-vuejs',
          '/docs/technologies/retrieve-the-group-field-gatsby-birkir',
          '/docs/technologies/retrieve-the-document-object-gatsby',
          '/docs/technologies/configure-your-project-nextjs',
          '/docs/query-by-a-content-relationship-or-link-field-graphql',
          '/docs/technologies/date-time-based-predicate-reference-nodejs',
          '/docs/technologies/add-the-navigation-nuxtjs',
          '/docs/technologies/rendering-links-or-link-to-media-fields-gatsby-birkir',
          '/docs/core-concepts/manage-users',
          '/docs/technologies/fetch-linked-document-content-graphql',
          '/docs/technologies/query-by-date-nodejs',
          '/docs/technologies/date-templating-dotnet',
          '/docs/technologies/date-time-based-predicate-reference-vuejs',
          '/docs/technologies/fetch-linked-document-fields-javascript',
          '/docs/technologies/order-your-results-javascript',
          '/docs/technologies/deployment-rebuilding-nextjs',
          '/docs/technologies/route-resolver-nuxtjs',
          '/docs/technologies/templating-slices-nodejs',
          '/docs/technologies/running-your-project-nextjs',
          '/docs/technologies/query-with-the-slice-zone-nuxtjs',
          '/docs/technologies/query-by-id-or-uid-laravel',
          '/docs/technologies/order-your-results-reactjs',
          '/docs/technologies/start-from-scratch-php',
          '/docs/technologies/fulltext-search-reactjs',
          '/docs/technologies/rendering-the-rich-text-and-title-field-reactjs',
          '/docs/templating-image-field-ruby',
          '/docs/technologies/paginate-your-results-graphql',
          '/docs/technologies/templating-timestamp-field-java',
          '/docs/integrating-with-an-existing-project-vuejs',
          '/docs/technologies/log-in-with-the-cli-nextjs',
          '/docs/previews-and-the-prismic-toolbar-graphql',
          '/docs/technologies/query-options-reference-vuejs',
          '/docs/technologies/preview-gatsby',
          '/docs/technologies/code-style-components-nextjs',
          '/docs/technologies/create-homepage-banner-nextjs',
          '/docs/core-concepts/reusing-slices',
          '/docs/technologies/previews-and-the-prismic-toolbar-vuejs',
          '/docs/technologies/quick-start-nuxtjs',
          '/docs/technologies/anatomy-of-a-query-gatsby',
          '/docs/technologies/seo-nuxtjs',
          '/docs/templating-date-field-java',
          '/docs/technologies/link-resolver-javascript',
          '/docs/integrating-with-an-existing-javascript-project',
          '/docs/technologies/templating-content-nextjs',
          '/docs/technologies/publish-a-slice-library-nextjs',
          '/docs/how-to-query-the-api-javascript',
          '/docs/integrating-with-an-existing-react-project',
          '/docs/technologies/templating-rich-text-and-title-fields-nodejs',
          '/docs/technologies/query-by-tag-vuejs',
          '/docs/technologies/query-by-date-reactjs',
          '/docs/technologies/customise-the-default-library-nuxtjs',
          '/docs/technologies/query-by-a-field-rest-api',
          '/docs/core-concepts/navigate-languages-copy-content',
          '/docs/technologies/templating-rich-text-and-title-fields-java',
          '/docs/core-concepts/import-json-reference',
          '/docs/technologies/vue-template-content',
          '/docs/technologies/templating-number-field-nodejs',
          '/docs/technologies/install-npm-nuxtjs',
          '/docs/technologies/deployment-and-previews-nuxtjs',
          '/docs/technologies/query-a-single-type-document-vuejs',
          '/docs/technologies/getting-started-vuejs',
          '/docs/technologies/reactjs',
          '/docs/technologies/html-serializer-nextjs',
          '/docs/technologies/basics-on-querying-the-graphql-api',
          '/docs/technologies/send-slices-prismic-nextjs',
          '/docs/technologies/rendering-the-embed-field-gatsby',
          '/docs/technologies/query-helper-functions-reactjs',
          '/docs/technologies/vue-seo',
          '/docs/core-concepts/image',
          '/docs/technologies/fulltext-search-rest-api',
          '/docs/technologies/query-by-id-or-uid-javascript',
          '/docs/technologies/gatsby-example-projects',
          '/docs/technologies/query-by-date-or-timestamp-gatsby',
          '/docs/technologies/use-multiple-predicates-rest-api',
          '/docs/test-page',
          '/docs/query-by-content-relationship-javascript',
          '/docs/technologies/integrating-with-an-existing-react-project',
          '/docs/technologies/templating-the-group-field-graphql',
          '/docs/technologies/create-and-model-a-component-nextjs',
          '/docs/technologies/migration-guide-gatsby',
          '/docs/technologies/rendering-the-group-field-reactjs',
          '/docs/technologies/templating-key-text-field-javascript',
          '/docs/query-by-date-or-timestamp-gatsby',
          '/docs/core-concepts/link-content-relationship',
          '/docs/technologies/navbars-footers-menus-nextjs',
          '/docs/technologies/query-by-tags-reactjs',
          '/docs/technologies/react-with-graphql',
          '/docs/technologies/multi-language-website-example-with-gatsby',
          '/docs/technologies/tutorial-5-add-navigation-gatsby',
          '/docs/technologies/languages-and-localization-gatsby',
          '/docs/technologies/templating-date-field-laravel',
          '/docs/technologies/query-with-the-prismic-object-nuxtjs',
          '/docs/technologies/fetch-linked-document-fields-ruby',
          '/docs/technologies/query-similar-documents-gatsby',
          '/docs/order-your-results-javascript',
          '/docs/technologies/gatsby-birkir-tutorial-4-adding-repeatable-pages',
          '/docs/technologies/templating-timestamp-field-php',
          '/docs/technologies/start-from-scratch-nodejs',
          '/docs/technologies/query-anatomy-gatsby',
          '/docs/technologies/query-rich-text-dotnet',
          '/docs/technologies/rest-api-technical-reference',
          '/docs/technologies/browse-the-api-with-postman',
          '/docs/technologies/templating-rich-text-and-title-fields-php',
          '/docs/technologies/seo-with-reactjs-and-prismic',
          '/docs/gatsby-tutorial-1-launching-the-project',
          '/docs/getting-started-java',
          '/docs/technologies/the-response-object-reactjs',
          '/docs/query-by-type-java',
          '/docs/technologies/render-the-uid-field-reactjs',
          '/docs/technologies/gatsby-birkir-anatomy-of-a-query',
          '/docs/technologies/link-resolver-nuxtjs',
          '/docs/technologies/rendering-the-rich-text-or-title-field-gatsby-birkir',
          '/docs/technologies/previews-hocs-gatsby',
          '/docs/technologies/html-serializer-reactjs',
          '/docs/technologies/retrieve-the-group-field-gatsby',
          '/docs/technologies/query-by-prismic-content-fields-gatsby',
          '/docs/technologies/content-outside-of-the-slicezone-nextjs',
          '/docs/technologies/example-projects-gatsby',
          '/docs/technologies/example-projects-php',
          '/docs/technologies/retrieve-group-content',
          '/docs/technologies/fetch-linked-document-fields-laravel',
          '/docs/technologies/templating-key-text-field-vuejs',
          '/docs/technologies/create-more-components-nextjs',
          '/docs/technologies/query-by-content-relationship-rest-api',
          '/docs/technologies/storybook-nextjs',
          '/docs/technologies/example-projects-with-graphql',
          '/docs/technologies/vue-setup',
          '/docs/using-prismic-with-nuxtjs-vuejs',
          '/docs/core-concepts/version-documents',
          '/docs/technologies/how-to-query-the-api-nodejs',
          '/docs/order-your-results-gatsby',
          '/docs/technologies/retrieve-slice-content-gatsby-birkir',
          '/docs/technologies/order-your-results-nodejs',
          '/docs/technologies/order-your-results-rest-api',
          '/docs/technologies/paginate-your-results-gatsby',
          '/docs/technologies/libraries-nuxtjs',
          '/docs/technologies/introspection-fragment-matching-with-graphql',
          '/docs/query-a-single-document-gatsby',
          '/docs/core-concepts/import-export',
          '/docs/technologies/query-by-a-field-nodejs',
          '/docs/technologies/query-all-your-documents-vuejs',
          '/docs/technologies/query-a-single-type-document-javascript',
          '/docs/technologies/query-options-reference-reactjs',
          '/docs/technologies/integrating-with-an-existing-project-php',
          '/docs/technologies/link-resolver-gatsby',
          '/docs/technologies/rendering-the-number-field-reactjs',
          '/docs/technologies/templating-slices-gatsby',
          '/docs/technologies/rendering-the-key-text-field-gatsby-birkir',
          '/docs/technologies/troubleshooting-gatsby',
          '/docs/technologies/retrieve-slices-gatsby',
          '/docs/technologies/retrieve-link-field-content-graphql',
          '/docs/technologies/retrieve-prismic-fields-gatsby',
          '/docs/platforms',
          '/docs/technologies/retrieve-the-document-object-graphql',
          '/docs/technologies/previews-and-prismic-toolbar-java',
          '/docs/technologies/query-by-tags-graphql',
          '/docs/technologies/fulltext-search-gatsby-birkir',
          '/docs/technologies/query-by-type-vuejs',
          '/docs/technologies/query-api-nextjs',
          '/docs/technologies/templating-the-link-and-content-relationship-field-graphql',
          '/docs/technologies/gatsby',
          '/docs/technologies/templating-fields-gatsby',
          '/docs/core-concepts/content-modeling-with-json',
          '/docs/technologies/step-by-step-guide-gatsby',
          '/docs/core-concepts',
          '/docs/technologies/query-predicates-reference-rest-api',
          '/docs/technologies/query-by-tags-gatsby',
          '/docs/technologies/previews-and-the-prismic-toolbar-javascript',
          '/docs/technologies/templating-image-field-javascript',
          '/docs/query-predicates-reference-reactjs',
          '/docs/core-concepts/edit-rich-text',
          '/docs/technologies/fulltext-search-vuejs',
          '/docs/technologies/arguments-filter-sort-limit-skip-gatsby',
          '/docs/technologies/links-content-relationships-nextjs',
          '/docs/technologies/imgix-optimization-and-gatsby-image-birkir',
          '/docs/technologies/query-all-your-documents-gatsby-birkir',
          '/docs/technologies/prismic-plugins-gatsby',
          '/docs/core-concepts/languages-locales',
          '/docs/technologies/migrate-to-the-recommended-plugin-gatsby',
          '/docs/query-predicates-reference-rest-api',
          '/docs/technologies/templating-rich-text-gatsby',
          '/docs/technologies/link-resolver-nodejs',
          '/docs/technologies/configure-the-plugin-gatsby',
          '/docs/technologies/vue-slices',
          '/docs/technologies/pagination-for-results-php',
          '/docs/technologies/deployment-php',
          '/docs/test-pagez',
          '/docs/technologies/the-document-object-javascript',
          '/docs/technologies/vue-slicezone-technical-reference',
          '/docs/technologies/query-by-id-or-uid-gatsby',
          '/docs/technologies/tutorial-6-preview-deploy-gatsby',
          '/docs/gatsby-tutorial-5-adding-the-navigation',
          '/docs/technologies/query-by-content-relationship-or-link-gatsby',
          '/docs/technologies/query-helper-functions-vuejs',
          '/docs/date-time-based-predicate-reference-vuejs',
          '/docs/technologies/create-your-own-slices-components-nuxtjs',
          '/docs/technologies/seo-nextjs',
          '/docs/core-concepts/test-page-2',
          '/docs/how-to-query-the-api-dotnet',
          '/docs/technologies/rendering-the-key-text-field-gatsby',
          '/docs/technologies/date-time-based-predicate-reference-laravel',
          '/docs/core-concepts/previews',
          '/docs/technologies/gatsby-birkir-tutorial-2-convert-the-static-homepage-banner',
          '/docs/technologies/using-prismic-with-nuxtjs-vuejs',
          '/docs/technologies/query-all-documents-rest-api',
          '/docs/technologies/create-a-prismicio-client-rest-api',
          '/docs/prismic-core-concepts-development-workflow',
          '/docs/technologies/what-does-the-prismic-repo-do-nuxtjs',
          '/docs/technologies/tutorial-series-introduction-nuxtjs',
          '/docs/technologies/configure-your-project-nuxtjs',
          '/docs/query-by-a-field-rest-api',
          '/docs/technologies/templating-date-field-nodejs',
          '/docs/technologies/query-all-your-documents-nodejs',
          '/docs/technologies/how-to-query-the-api-javascript',
          '/docs/technologies/templating-image-field-vuejs',
          '/docs/technologies/query-content-from-cms-nuxtjs',
          '/docs/core-concepts/translate-content-in-bulk',
          '/docs/technologies/how-to-query-the-api-dotnet-asdf',
          '/docs/technologies/installing-npm-nuxtjs',
          '/docs/technologies/templating-timestamp-field-javascript',
          '/docs/technologies/getting-started-php',
          '/docs/technologies/does-prismic-have-a-write-api',
          '/docs/technologies/retrieve-links-or-content-relationships-gatsby',
          '/docs/technologies/query-by-language-reactjs',
          '/docs/technologies/query-by-language-graphql',
          '/docs/technologies/previews-gatsby',
          '/docs/technologies/templating-group-field-javascript',
          '/docs/technologies/launch-an-example-slice-machine-project-next.js',
          '/docs/technologies/reacting-to-parameter-changes-vuejs',
          '/docs/technologies/technical-references',
          '/docs/technologies/templating-date-field-ruby',
          '/docs/technologies/plugin-configuration-gatsby',
          '/docs/technologies/retrieve-prismic-content-fields-gatsby-birkir',
          '/docs/core-concepts/how-to-import-content',
          '/docs/technologies/rendering-the-slice-zone-gatsby-birkir',
          '/docs/technologies/deployment-rebuilding-previewing-nuxtjs',
          '/docs/technologies/query-by-uid-dotnet',
          '/docs/technologies/query-a-single-document-gatsby',
          '/docs/query-by-id-or-uid-gatsby',
          '/docs/technologies/how-to-query-the-api-with-dotnet',
          '/docs/technologies/date-time-based-predicate-reference-javascript',
          '/docs/technologies/run-view-project-preview-nuxtjs',
          '/docs/technologies/prismic-gatsby-source-graphql-plugin',
          '/docs/technologies/query-by-id-or-uid-java',
          '/docs/technologies/start-a-prismic-project-from-scratch-with-reactjs',
          '/docs/technologies/templating-rich-text-and-title-fields-vuejs',
          '/docs/technologies/the-response-object-ruby',
          '/docs/fetch-linked-document-fields-php',
          '/docs/technologies/rendering-the-embed-field-reactjs',
          '/docs/how-to-query-the-api-with-javascript',
          '/docs/technologies/tutorial-series-introduction-nextjs',
          '/docs/technologies/templating-color-field-vuejs',
          '/docs/technologies/templating-image-field-nodejs',
          '/docs/technologies/query-a-single-type-document-reactjs',
          '/docs/technologies/templating-select-field-nodejs',
          '/docs/technologies/integrate-with-existing-js-project-graphql',
          '/docs/technologies/technical-reference-next-slicezone-nextjs',
          '/docs/technologies/prismic-and-gatsby-cloud-gatsby',
          '/docs/technologies/configure-project-manually-nuxtjs',
          '/docs/core-concepts/test-page-1b',
          '/docs/technologies/rendering-the-embed-field-gatsby-birkir',
          '/docs/technologies/templating-timestamp-field-ruby',
          '/docs/technologies/vue-query',
          '/docs/technologies/gatsby-tutorial-6-setting-up-previews',
          '/docs/technologies/query-helper-functions-nodejs',
          '/docs/technologies/template-content-nuxtjs',
          '/docs/core-concepts/troubleshooting-import-export',
          '/docs/technologies/example-projects-reactjs',
          '/docs/technologies/rendering-the-image-field-gatsby',
          '/docs/technologies/templating-the-date-field-graphql',
          '/docs/technologies/getting-started-nuxtjs',
          '/docs/technologies/custom-types-api',
          '/docs/core-concepts/editing-intro',
          '/docs/technologies/javascript',
          '/docs/technologies/deploying-your-gatsby-website',
          '/docs/technologies/rendering-multi-language-info-reactjs',
          '/docs/technologies/order-your-results-gatsby',
          '/docs/technologies/rendering-the-select-field-gatsby',
          '/docs/technologies/query-by-language-nodejs',
          '/docs/technologies/nav-bars-footers-and-menus-nuxtjs',
          '/docs/technologies/fragments-gatsby',
          '/docs/technologies/prismic-cli-commands-options-nextjs',
          '/docs/technologies/paginate-results-gatsby',
          '/docs/technologies/adding-a-storybook-nextjs',
          '/docs/the-response-object-javascript',
          '/docs/technologies/query-helper-functions-javascript',
          '/docs/technologies/templating-rich-text-and-title-fields-javascript',
          '/docs/technologies/libraries-and-tools-rest-api',
          '/docs/core-concepts/custom-types',
          '/docs/technologies/write-api',
          '/docs/technologies/templating-link-and-content-relationship-fields-nodejs',
          '/docs/gatsby',
          '/docs/technologies/how-to-query-the-api-ruby',
          '/docs/technologies/query-all-documents-graphql',
          '/docs/technologies/integrate-prismic-with-an-existing-project-ruby',
          '/docs/technologies/query-predicate-reference-php',
          '/docs/technologies/gatsby-birkir-getting-started-tutorials',
          '/docs/technologies/order-your-results-gatsby-birkir',
          '/docs/technologies/fetch-linked-document-fields-rest-api',
          '/docs/technologies/query-by-type-reactjs',
          '/docs/technologies/templating-date-field-php',
          '/docs/technologies/getting-started-java',
          '/docs/technologies/prismic-cli-commands-options-nuxtjs',
          '/docs/core-concepts/document-tags',
          '/docs/technologies/query-similar-documents-graphql',
          '/docs/prismic-gatsby-source-plugin',
          '/docs/core-concepts/uid',
          '/docs/technologies/query-basics-gatsby',
          '/docs/technologies/the-document-object-nodejs',
          '/docs/integrating-with-an-existing-javascript-projectz',
          '/docs/technologies/install-the-cli-nuxtjs',
          '/docs/technologies/sign-in-to-the-cli-nuxtjs',
          '/docs/technologies/query-by-id-rest-api',
          '/docs/technologies/rendering-content-relationships-gatsby',
          '/docs/core-concepts/content-modeling',
          '/docs/query-options-reference-java',
          '/docs/technologies/query-options-reference-javascript',
          '/docs/technologies/prismic-and-nextjs',
          '/docs/technologies/templating-uid-field-javascript',
          '/docs/technologies/sample-blog-with-prismic-and-gatsby',
          '/docs/technologies/pagination-for-results-vuejs',
          '/docs/technologies/prismic-and-gatsby-plugins-gatsby',
          '/docs/technologies/the-route-resolver-nuxtjs',
          '/docs/technologies/html-serializer-vuejs',
          '/docs/technologies/templating-geopoint-field-vuejs',
          '/docs/technologies/query-by-date-javascript',
          '/docs/technologies/order-your-results-vuejs',
          '/docs/getting-started-from-scratch-with-nextjs',
          '/docs/technologies/use-the-default-library-nextjs',
          '/docs/technologies/vue-route-parameters',
          '/docs/technologies/advanced-rich-text-templating-nextjs',
          '/docs/technologies/rendering-the-color-field-gatsby',
          '/docs/technologies/date-time-based-predicate-reference-ruby',
          '/docs/technologies/integrating-with-an-existing-project-nodejs',
          '/docs/technologies/the-nuxt-config-file',
          '/docs/core-concepts/archive-delete',
          '/docs/introduction-to-the-content-query-api',
          '/docs/technologies/rendering-the-metadata-gatsby',
          '/docs/technologies/tutorial-6-previews-and-deployment-gatsby',
          '/docs/search-parameters-reference-rest-api',
          '/docs/technologies/integrating-with-an-existing-project-javascript',
          '/docs/technologies/tutorial-2-create-homepage-banner-gatsby',
          '/docs/technologies/tutorial-gatsby',
          '/docs/core-concepts/import-new-content-in-multiple-languages',
          '/docs/technologies/templating-select-field-javascript',
          '/docs/technologies/tutorial-2-create-a-homepage-banner-gatsby',
          '/docs/query-all-documents-graphql',
          '/docs/technologies/gatsby-birkir',
          '/docs/query-by-prismic-content-fields-gatsby',
          '/docs/core-concepts/test-2a',
          '/docs/technologies/add-content-and-query-the-cms-nextjs',
          '/docs/technologies/templating-multi-language-info-vuejs',
          '/docs/technologies/installing-npm-nextjs',
          '/docs/technologies/the-graphql-api-explorer',
          '/docs/technologies/how-to-query-the-api-dotnet',
          '/docs/technologies/the-document-object-vuejs',
          '/docs/technologies/homepage-reactjs',
          '/docs/query-by-content-relationship-or-link-gatsby',
          '/docs/technologies/prismic-cli-technical-reference',
          '/docs/core-concepts/draft-plan-and-schedule-content',
          '/docs/technologies/html-serializer-nuxtjs',
          '/docs/core-concepts/your-prismic-profile',
          '/docs/technologies/retrieve-slice-content-gatsby',
          '/docs/technologies/query-predicates-reference-reactjs',
          '/docs/technologies/rendering-the-geopoint-field-reactjs',
          '/docs/prismic-core-concepts',
          '/docs/technologies/template-links-gatsby',
          '/docs/technologies/templating-group-field-vuejs',
          '/docs/technologies/template-images-gatsby',
          '/docs/technologies/rendering-the-image-field-gatsby-birkir',
          '/docs/technologies/deploydment--rebuilding-nuxtjs',
          '/docs/technologies/fulltext-search-graphql',
          '/docs/core-concepts/test-page-2b',
          '/docs/technologies/rendering-the-number-field-gatsby',
          '/docs/technologies/rich-text-templating-dotnet',
          '/docs/core-concepts/document-display-name',
          '/docs/query-by-tags-gatsby',
          '/docs/query-helper-functions-nodejs',
          '/docs/technologies/link-resolving-gatsby',
          '/docs/getting-started-laravel',
          '/docs/technologies/gatsby-birkir-tutorial-1-launching-the-project',
          '/docs/intro-to-the-graphql-api',
          '/docs/technologies/sample-multi-page-website-with-navigation-nuxtjs',
          '/docs/technologies/rendering-the-key-text-field-reactjs',
          '/docs/query-by-date-rest-api',
          '/docs/integrate-with-existing-js-project-graphql',
          '/docs/date-and-time-based-predicate-reference-rest-api',
          '/docs/technologies/intro-to-the-graphql-api',
          '/docs/technologies/running-the-prismic-slice-machine-command-nextjs',
          '/docs/technologies/run-the-prismic-slice-machine-command-nuxtjs',
          '/docs/technologies/query-by-type-nodejs',
          '/docs/technologies/rendering-the-rich-text-or-title-field-gatsby',
          '/docs/technologies/templating-timestamp-field-nodejs',
          '/docs/how-to-query-the-api-vuejs',
          '/docs/technologies/rendering-the-timestamp-field-gatsby',
          '/docs/gatsby-tutorial-2-convert-the-static-homepage-banner',
          '/docs/technologies/multi-language-templating-javascript',
          '/docs/technologies/nuxtjs',
          '/docs/technologies/create-a-new-app-nextjs',
          '/docs/technologies/prismicio-client-technical-reference',
          '/docs/technologies/rendering-the-group-field-gatsby',
          '/docs/technologies/query-all-your-documents-javascript',
          '/docs/technologies/the-slice-builder-nextjs',
          '/docs/technologies/add-the-dev-tools-to-an-existing-project-nextjs',
          '/docs/technologies/fetch-linked-document-fields-reactjs',
          '/docs/technologies/deploy-gatsby',
          '/docs/technologies/deployment-and-previews-nextjs',
          '/docs/gatsby-getting-started-tutorials',
          '/docs/technologies/vuejs',
          '/docs/technologies/query-by-a-field-vuejs',
          '/docs/technologies/the-rest-api-browser'
        ],
        weight: 2,
        queryTotal: 1,
        updated: 1622046910863,
        title: 'Layout',
        summary: 'Documentation',
        singleton: true,
        editorUrl: 'https://prismicio-docs-v3.prismic.io/documents~c=published&l=en-us/Xej8gREAACQApSU3/',
        isDocumentLink: false,
        status: 'live'
      },
      {
        id: 'X7-aHRAAACQApLWn',
        urls: [
          '/docs/technologies/lifecycle-hooks-nextjs',
          '/docs/technologies/create-a-page-add-content--publish-nextjs',
          '/docs/technologies/navbars-footers-and-menus-nextjs',
          '/docs/technologies/getting-started-with-slice-machine-nextjs',
          '/docs/technologies/customization-nextjs',
          '/docs/technologies/getting-started-nextjs',
          '/page/2',
          '/page/4',
          '/docs/technologies/previews-nextjs',
          '/docs/technologies/build-a-page-with-slices-nextjs',
          '/docs/technologies/quick-start-nextjs',
          '/docs/technologies/query-a-singleton-type-nextjs',
          '/docs/technologies/create-your-own-slices-components-nextjs',
          '/docs/technologies/adding-the-slicezone-component-nextjs',
          '/docs/technologies/home-prismic-and-nextjs',
          '/docs/technologies/the-route-resolver-nextjs',
          '/docs/technologies/install-the-prismic-cli-nextjs',
          '/docs/technologies/deployment-rebuilding-nextjs',
          '/page/1',
          '/docs/technologies/running-your-project-nextjs',
          '/docs/technologies/query-by-uid-nextjs',
          '/docs/technologies/log-in-with-the-cli-nextjs',
          '/docs/technologies/code-style-components-nextjs',
          '/docs/technologies/templating-content-nextjs',
          '/docs/technologies/publish-a-slice-library-nextjs',
          '/docs/technologies/html-serializer-nextjs',
          '/docs/technologies/send-slices-prismic-nextjs',
          '/docs/technologies/create-and-model-a-component-nextjs',
          '/docs/technologies/navbars-footers-menus-nextjs',
          '/docs/technologies/content-outside-of-the-slicezone-nextjs',
          '/docs/technologies/storybook-nextjs',
          '/page/3',
          '/docs/technologies/query-api-nextjs',
          '/docs/technologies/links-content-relationships-nextjs',
          '/docs/technologies/seo-nextjs',
          '/docs/technologies/launch-an-example-slice-machine-project-next.js',
          '/docs/technologies/technical-reference-next-slicezone-nextjs',
          '/page/6',
          '/docs/technologies/getting-started-examples-simple-nextjs',
          '/docs/technologies/prismic-cli-commands-options-nextjs',
          '/docs/technologies/adding-a-storybook-nextjs',
          '/page/5',
          '/docs/technologies/use-the-default-library-nextjs',
          '/docs/technologies/advanced-rich-text-templating-nextjs',
          '/page/21',
          '/docs/user-feedback-dashboard/ratings/Next.js',
          '/docs/technologies/running-the-prismic-slice-machine-command-nextjs',
          '/docs/technologies/create-a-new-app-nextjs',
          '/docs/technologies/the-slice-builder-nextjs',
          '/docs/technologies/add-the-dev-tools-to-an-existing-project-nextjs'
        ],
        weight: 1,
        queryTotal: 1,
        updated: 1622046911061,
        title: 'Sidebar - Next.js',
        summary: 'Next.js Home',
        singleton: false,
        editorUrl: 'https://prismicio-docs-v3.prismic.io/documents~c=published&l=en-us/X7-aHRAAACQApLWn/',
        isDocumentLink: false,
        status: 'live'
      },
      {
        id: 'X8dLGhAAAB8ASl3q',
        urls: [
          '/docs/technologies/tutorial-1-launch-the-project-gatsby',
          '/docs/technologies/tutorial-1-launch-project-gatsby',
          '/docs/technologies/fragments-in-gatsby',
          '/docs/technologies/tutorial-3-create-homepage-slices-gatsby',
          '/docs/technologies/template-fields-gatsby',
          '/docs/technologies/recreate-the-banner-as-a-component-nuxtjs',
          '/docs/technologies/paginate-the-results-gatsby',
          '/docs/technologies/sample-blog-gatsby',
          '/docs/technologies/sample-multi-lang-site-gatsby',
          '/docs/technologies/template-slices-gatsby',
          '/docs/technologies/languages-localization-gatsby',
          '/docs/technologies/templating-links-gatsby',
          '/docs/technologies/tutorial-5-add-the-navigation-gatsby',
          '/docs/technologies/home-prismic-and-nextjs',
          '/docs/technologies/templating-images-gatsby',
          '/docs/technologies/preview-gatsby',
          '/docs/technologies/anatomy-of-a-query-gatsby',
          '/docs/technologies/migration-guide-gatsby',
          '/docs/technologies/multi-language-website-example-with-gatsby',
          '/docs/technologies/tutorial-5-add-navigation-gatsby',
          '/docs/technologies/query-anatomy-gatsby',
          '/docs/technologies/deployment-gatsby',
          '/docs/technologies/previews-hocs-gatsby',
          '/docs/technologies/example-projects-gatsby',
          '/docs/technologies/link-resolver-gatsby',
          '/docs/technologies/templating-slices-gatsby',
          '/docs/technologies/troubleshooting-gatsby',
          '/docs/technologies/retrieve-slices-gatsby',
          '/docs/technologies/retrieve-prismic-fields-gatsby',
          '/docs/technologies/gatsby',
          '/docs/technologies/templating-fields-gatsby',
          '/docs/technologies/step-by-step-guide-gatsby',
          '/docs/technologies/arguments-filter-sort-limit-skip-gatsby',
          '/docs/technologies/prismic-plugins-gatsby',
          '/docs/technologies/migrate-to-the-recommended-plugin-gatsby',
          '/docs/technologies/templating-rich-text-gatsby',
          '/docs/technologies/configure-the-plugin-gatsby',
          '/docs/technologies/tutorial-6-preview-deploy-gatsby',
          '/docs/technologies/manual-previews-gatsby',
          '/docs/technologies/previews-gatsby',
          '/docs/technologies/plugin-configuration-gatsby',
          '/docs/technologies/template-rich-text-gatsby',
          '/docs/technologies/tutorial-4-add-dynamic-pages-gatsby',
          '/docs/technologies/prismic-and-gatsby-cloud-gatsby',
          '/docs/technologies/paginate-results-gatsby',
          '/docs/technologies/query-basics-gatsby',
          '/docs/technologies/sample-blog-with-prismic-and-gatsby',
          '/docs/technologies/prismic-and-gatsby-plugins-gatsby',
          '/docs/technologies/tutorial-6-previews-and-deployment-gatsby',
          '/docs/technologies/tutorial-2-create-homepage-banner-gatsby',
          '/docs/technologies/tutorial-gatsby',
          '/docs/technologies/tutorial-2-create-a-homepage-banner-gatsby',
          '/docs/technologies/gatsby-birkir',
          '/docs/technologies/template-links-gatsby',
          '/docs/technologies/template-images-gatsby',
          '/docs/technologies/deploy-gatsby'
        ],
        weight: 1,
        queryTotal: 1,
        updated: 1622036678641,
        title: 'Sidebar: Gatsby',
        summary: 'Home',
        singleton: false,
        editorUrl: 'https://prismicio-docs-v3.prismic.io/documents~c=published&l=en-us/X8dLGhAAAB8ASl3q/',
        isDocumentLink: false,
        status: 'live'
      }
    ];

    const result = sortDocsWithLocation(docs, location);

    expect(result[0].title).toBe('Sidebar - Next.js');

  });
});
